#!/usr/bin/env bash

#
# github.com/suhlig/bosh-rsync-blobs
#
# Make this easier by copying your public key to your rsync server's home directory. Either use ssh-copy-id
# or this script (beware, this will overwrite .ssh/authorized_keys on the remote side):
#
# scp ~/.ssh/id_rsa.pub example.com:.ssh/authorized_keys
#

if [[ -z "$RSYNC_URL" ]]; then
  >&2 echo "Error: RSYNC_URL is required, but not present."
  exit 1
fi

BLOBS_DIR=.blobs

if [[ ! -d "$BLOBS_DIR" ]]; then
  >&2 echo "Error: $BLOBS_DIR does not exist in $PWD - is this really a BOSH release directory?"
  exit 1
fi

>&2 echo "Downloading blobs from $RSYNC_URL"
rsync --rsh=ssh --recursive --progress --human-readable "$RSYNC_URL"/ "$BLOBS_DIR"

>&2 echo
>&2 echo "Synching blobs with the BOSH director"
bosh target
bosh sync blobs

>&2 echo
>&2 echo "Uploading blobs to $RSYNC_URL"
rsync --rsh=ssh --recursive --progress --human-readable "$BLOBS_DIR"/ "$RSYNC_URL"
